In [1]:
import glob
import pandas as pd
import numpy as np
import os, sys
import collections

In [2]:
import numpy as np
import pandas as pd
from sklearn.metrics import f1_score
from sklearn.model_selection import KFold
from sklearn.model_selection import LeaveOneGroupOut
from sklearn.model_selection import cross_val_score


from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, roc_auc_score
from sklearn.feature_selection import VarianceThreshold
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import GradientBoostingClassifier

In [3]:
from numba.typed import List
from numba import jit, njit, vectorize

In [4]:
from sklearn import preprocessing

In [5]:
sample_rate = 50  # number of observation per second based on dataset documentation(150 samples in 3 second)

sliding_size = int((1/3) * sample_rate)  # number of skipped datapoints to start next window
print(sliding_size)

16

# Feature sets

In [6]:
@njit()
def mean_crossing_rate(col):
    # col = np.array(values)
    normalized = col - col.mean()  # to make elements of array possitive or negetive
    return ((normalized[:-1] * col[1:]) < 0).sum()  # Zero-Crossing_rate

@njit()
def iqr(window):  # inter-quartile range
    Q1 = np.median(window[:len(window)//2])  # First quartile (Q1) 
    Q3 = np.median(window[len(window)//2:])  # Third quartile (Q3) 
    IQR = Q3 - Q1 # Interquartile range (IQR) 
    return(IQR) 
@njit()
def calc_sma_for_window(data):
    return np.sum(data) / len(data)  
@njit()
def get_min(x):
    m = np.min(x)
    return m
@njit()
def get_max(x):
    m = np.max(x)
    return m
@njit()
def get_mean(x):
    m = np.mean(x)
    return m
@njit()
def get_var(x):
    m = np.var(x)
    return m
@njit()
def get_mean(x):
    m = np.mean(x)
    return m
@njit()
def get_sum(x):
    m = x.sum()
    return m 
@njit()
def get_median(x):
    m = np.median(x)
    return m 
@njit()
def get_std(x):
    m = np.median(x)
    return m

In [7]:
def Energy(frame):
    return sum( [ abs(x)**2 for x in frame ] ) / len(frame)

# Mean removal on signal

In [8]:
def Features(window):# mean, std,max,min and zero-crossing-rate
    win = np.array(window[:,:-1])
    
    data_standardized = preprocessing.scale(win) # mean removal
    win = data_standardized
    
    features = []
    
    features.append(get_mean(win))
    features.append(get_median(win))
    features.append(get_var(win))
    features.append(get_std(win))
    features.append(get_min(win))
    features.append(get_max(win))
    features.append(get_sum(win))
    mean_crossing = [mean_crossing_rate(win[:, i]) for i in range(win.shape[1])]
    features.append(np.array(mean_crossing))
    IQR = iqr(win)
    features.append(np.array(IQR))
    energy_measure = Energy(win)
    features.append(np.array(energy_measure))
 

    features = np.hstack(features).tolist()

    label = window.iloc[:, -1].mode()[0]  ## select the most frequent label as the label of the window
    features.append(label)
    return features

In [9]:
def windowing_dataset(dataset, win_size, feature_extraction_function, subject_id, overlap=False):
    windowed_dataset = []
    win_count = 0
    if overlap:
        step_size = sliding_size  # for Overlapping technique
    else:
        step_size = win_size  # for Non-overlapping technique

    for index in range(0, dataset.shape[0], step_size):
        start = index
        end = start + win_size
        # to assure all of windows are equal in size
        if (end <= dataset.shape[0]):
            window = dataset.iloc[start:end, :].reset_index(drop=True)
            win_count = win_count + 1
            features = feature_extraction_function(window)

            windowed_dataset.append(features)

    final = pd.DataFrame(windowed_dataset)
    final.insert(0, 'group', subject_id)  # to use in Subject CV
    return final

In [10]:
def Preprocessing(dataset_path, overlapping):
    feature_function = Features
    win_size = 3
    print("Start for win size {}".format(win_size))
    datapoints_per_window = int(win_size * sample_rate)

    

    print(feature_function.__name__)

    windowed_dataset = []

    for subject in range(1,18):
        file_path = dataset_path + '\subject{0}_ideal.csv'.format(subject)
        acc_cols = []
        for i in range(11, 117, 13):# indices of accelarations
            indices = list(range(i, i + 4))
            acc_cols.extend(indices)

        acc_cols.append(119)  # label index

        tmp_db = pd.read_csv(file_path, header=None, usecols=acc_cols, sep='\t')
        tmp_db.columns = list(range(tmp_db.shape[1]))  # re-index the columns
        
        transformed_db = windowing_dataset(tmp_db, datapoints_per_window, feature_function, subject,
                                                   overlap=overlapping)

        windowed_dataset.append(transformed_db)

    final_dataset = pd.DataFrame()
    
    final_dataset = final_dataset.append(windowed_dataset, ignore_index=True)
    return final_dataset

In [11]:
def subject_cross_validation(X, Y, groups, classifier):
    f1 = []
    logo = LeaveOneGroupOut()

    for train_index, test_index in logo.split(X, Y, groups=groups):
        X_train, X_test = X[train_index], X[test_index]
        y_train, y_test = Y[train_index], Y[test_index]

        classifier.fit(X_train, y_train)

        y_pred = classifier.predict(X_test)
        f1.append(f1_score(y_true=y_test, y_pred=y_pred, average='micro'))
    return np.mean(f1)

In [12]:
def apply_classifiers(dataset, model, cv_strategy):
    results = dict()
    win_size = float(3)
    print('window_size = ', win_size,' sec')

    dataset = dataset
    groups = dataset['group']
    X = dataset.iloc[:, 1:-1].values

    Y = dataset.iloc[:, -1].values


    for model_name, mod in model.items():
        f1 = 0


        f1 = subject_cross_validation(X, Y, groups, mod)

        if win_size in results:
            results[win_size].append(f1)
        else:
            results[win_size] = [f1]

      
        results = collections.OrderedDict(sorted(results.items()))

        final = []
        col = list(model.keys())
        col.insert(0, "window-size")
        final.append(col)
        for k, v in results.items():
            tmp = []
            tmp.append([k])
            tmp.append(v)
            flattened = [val for sublist in tmp for val in sublist]
            final.append(flattened)

        print('accuracy : ', final[1][1])

In [13]:
mod = {'RF': RandomForestClassifier(n_estimators=100, random_state=0, n_jobs=-1)}

In [14]:
dataset_csv_path = r"D:\projec\proj\data"

overlapping = 1

df = Preprocessing(dataset_path=dataset_csv_path, overlapping=bool(int(overlapping)))

df.head(10)

Start for win size 3
FS3
Features

,group,0,1,2,3,4,5,6,7,8,...,72,73,74,75,76,77,78,79,80,81
0,1,1.728267e-15,0.000000,0.972973,0.000000,-3.342525,3.577405,9.527934e-12,74.0,72.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1
1,1,-1.130782e-15,0.000000,0.972973,0.000000,-3.006399,2.802637,-6.233999e-12,71.0,85.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1
2,1,-1.031080e-16,0.000000,0.972973,0.000000,-3.263367,3.138424,-5.684342e-13,66.0,85.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1
3,1,1.555480e-16,0.000000,0.972973,0.000000,-5.463698,5.945055,8.575363e-13,39.0,102.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1
4,1,3.112370e-16,0.052104,0.972973,0.052104,-4.562183,3.826219,1.715850e-12,32.0,104.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1
5,1,2.318922e-16,0.066938,0.972973,0.066938,-4.382536,2.939905,1.278422e-12,45.0,100.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1
6,1,-2.591292e-16,0.023727,0.972973,0.023727,-3.056619,2.323529,-1.428579e-12,56.0,95.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1
7,1,-4.218968e-17,0.067191,0.972973,0.067191,-6.273918,3.953576,-2.325917e-13,68.0,85.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1
8,1,2.091158e-16,0.000000,0.972973,0.000000,-3.063461,2.987323,1.152856e-12,81.0,82.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1
9,1,1.375041e-16,-0.009289,0.972973,-0.009289,-2.668813,2.696736,7.580603e-13,94.0,91.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1

In [15]:
dataset = df

apply_classifiers(dataset=dataset, model=mod, cv_strategy='sbj')

window_size =  3.0  sec
accuracy :  0.6634197318933881